### ISSUE TITLE
[Search] 인증 관련 아키텍쳐 구상

### ISSUE THREAD

**Issue by ujkkk** [edu-pi/Backend-User-Server#1]
## 📝 Description
**무엇을?**
-  인증 관련 아키텍쳐 구상

**왜?**
- (ex 사용자를 인증하기 위해)

## ❗️Todo
- [x] 세션과 토큰 차이
- [x] 게이트 웨이 조사
- [ ] 컴포넌트 다이어그램

## ETC
기타사항

**Comment by SongGwanSeok** [comment]
![Group 163](https://github.com/user-attachments/assets/9db7c753-6d58-4e3f-a6c8-67be98032e57)

일단 User기능 이외의 것들은 main으로 처리 이후에 분리 개발
