### ISSUE TITLE
[Search] RDB와 NoSql 중 조사 후 결정

### ISSUE THREAD

**Issue by ujkkk** [edu-pi/Backend-User-Server#2]

**Comment by ujkkk** [comment]
SQL과 NoSQL 차이

- SQL 구조화 쿼리 언어(SQL)를 사용하며 미리 정의된 스키마가 있습니다. NoSQL 데이터베이스에는 구조화되지 않은 데이터를 위한 동적 스키마가 있습니다.
- SQL 수직적 확장(중간에 새 테이블 추가 어렵)이 가능한 반면, NoSQL 데이터베이스는 수평적 확장이(수직적 확장 불가한가?) 가능합니다.
- SQL 테이블 기반인 반면, NoSQL 데이터베이스는 문서, 키-값, 그래프 또는 와이드 컬럼 스토어입니다.
- SQL은 Join 지원, NoSql은 미지원
- NoSQL은 유연성과 확장성이 더 뛰어나다

빠르고 확장 가능하며 안정적인 DB가 필요한 경우 NoSQL 적합,
복잡한 데이터 쿼리와 트랜잭션 지원이 필요한 경우 SQL이 더 나을 수도

![image](https://github.com/user-attachments/assets/6ec5ee51-8bbb-4972-b528-22f3108b1e2c)

SQL은 중간에 데이터 구조를 변경하는 것이 쉽지 않기 때문에 구축전 철저한 사전 준비가 필요하다. 사용할 스키마가 많으면, 시간이 길겠지만 우리는 회원 관리만 할 것이기 때문에 중간에 변경될만한 요소가 적다. 

회원관리를 할 때는 수직적으로만 늘어날 것 같아서 SQL이 더 적합한것 같다.

**Comment by SongGwanSeok** [comment]
RDB는 데이터 구조가 명확하며 변경 될 여지가 없으며 명확한 스키마가 중요한 경우 사용하는 것이 좋다. 또한 중복된 데이터가 없어 변경이 용이하기 때문에 관계를 맺고 있는 데이터가 자주 변경이 이루어지는 시스템에 적합.

NoSQL은 정확한 데이터 구조를 알 수 없고 데이터가 변경/확장이 될 수 있는 경우에 사용하는 것이 좋다. 하지만 데이터 중복이 발생할 수 있어 변경이 많이 이루어지지 않는 시스템이 좋고 또한 막대한 데이터를 저장하기 위해 수평확장(Scale-out) 해야 되는 시스템에 적합하다.

-> 회원 관리는 변경의 여지가 많이 없고 아직 수평확장에 대한 고려보다는 빠르게 구현하는 것이 중요하다고 생각하기 때문에 RDB를 사용
