### ISSUE TITLE
[Search] 회원관리 기능 스키마 구조 구상

### ISSUE THREAD

**Issue by ujkkk** [edu-pi/Backend-User-Server#3]
## 📝 Description
**무엇을?**
- 스키마 구조 

**왜?**
- 저장할 데이터와 스키마간의 관계 생각

## ❗️Todo
- [ ] 
- [ ] 
- [ ]

## ETC
기타사항

**Comment by SongGwanSeok** [comment]
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWY5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--37249b55f73bf2fdffa73815f1ddcce1a7d94818/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B5%E1%84%86%E1%85%A1.png" alt="스키마.png" />
